# ===============================
# CRONOS Smart Tambak Backend
# ===============================


    FROM node:23-alpine

    
    ENV NODE_ENV=development
    
    WORKDIR /app
    
    RUN apk add --no-cache \
        bash \
        tzdata \
        openssl \
        libc6-compat
    
    COPY package.json package-lock.json* ./
    
    RUN npm install
    
    COPY . .
    
    EXPOSE 9000
    
    HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
      CMD wget -qO- http://localhost:9000/api/health || exit 1
    
    CMD ["npm", "run", "dev:build"]
    